export const LANGUAGES = {
  ar: 'العربية [ar]',
  be: 'Беларуская мова [be]',
  bg: 'български език [bg]',
  bs: 'Bosanski [bs]',
  ca: 'català [ca]',
  cs: 'česky [cs]',
  da: 'dansk [da]',
  de: 'Deutsch [de]',
  el: 'Ελληνικά [el]',
  en: 'English [en]',
  eo: 'Esperanto [eo]',
  es: 'español [es]',
  et: 'eesti keel [et]',
  eu: 'Euskara [eu]',
  fa: 'فارسی [fa]',
  fi: 'suomi [fi]',
  fr: 'français [fr]',
  gd: 'Gàidhlig [gd]',
  he: 'עברית [he]',
  hi: 'मानक हिन्दी [hi]',
  hr: 'hrvatski [hr]',
  hu: 'Magyar [hu]',
  hy: 'Հայերեն լեզու [hy]',
  id: 'Bahasa Indonesia [id]',
  is: 'íslenska [is]',
  it: 'italiano (Italy) [it]',
  ja: '日本語 [ja]',
  ko: '한국어 [ko]',
  la: 'Latin [la]',
  lt: 'lietuvių kalba [lt]',
  lv: 'latviešu valoda [lv]',
  nl: 'Nederlands [nl]',
  nn: 'Nynorsk [nn]',
  no: 'Norsk [no]',
  pl: 'polski [pl]',
  pt: 'português [pt] (*)',
  ro: 'română [ro]',
  ru: 'русский [ru]',
  sk: 'slovenčina [sk]',
  sl: 'slovenščina [sl]',
  sr: 'српски језик [sr]',
  sv: 'Svenska [sv]',
  ta: 'தமிழ் [ta]',
  th: 'ภาษาไทย [th]',
  tr: 'Türkçe [tr]',
  uk: 'українська мова [uk]',
  vi: 'Tiếng Việt [vi]',
  zh: '中文 [zh]',
};
